#!/usr/bin/env nbb
;; hayari 流行 — regenerate data/m49-regions.edn (ISO 3166-1 alpha-2 -> UN M49).
;;
;;   nbb scripts/gen_regions.cljs
;;
;; The region axis has to come from a published standard rather than a hand-drawn
;; grouping, or "region" means whatever the author felt like that day. UN M49 is
;; the standard the rest of this workspace already uses — `etzhayyim/org.un.unstats`
;; stores UN SDG indicators under M49 `geoAreaCode` verbatim for the same reason.
;;
;; unstats.un.org publishes M49 as HTML only (probed 2026-08-10: 200, 1.7 MB of
;; markup, no JSON/CSV endpoint), so the machine-readable mirror below is used and
;; the provenance is written into the output rather than assumed by the reader.
;;
;; Written in nbb, not sh: the superproject forbids new shell scripts.

(ns gen-regions
  (:require ["fs" :as fs]
            [cljs.pprint :as pp]
            [clojure.string :as str]))

(def source-url
  "https://raw.githubusercontent.com/lukes/ISO-3166-Countries-with-Regional-Codes/master/all/all.json")

(def user-agent
  "hayari-observatory/0.1 (+https://github.com/cloud-itonami/hayari)")

(defn- blank->nil [s] (when-not (str/blank? s) s))

(defn -main [& _]
  (-> (js/fetch source-url #js {:headers #js {"User-Agent" user-agent}})
      (.then (fn [r]
               (if (.-ok r)
                 (.json r)
                 (throw (ex-info "region source fetch failed"
                                 {:status (.-status r) :url source-url})))))
      (.then
        (fn [rows]
          (let [today (.toISOString (js/Date.))
                m (into (sorted-map)
                        (keep (fn [o]
                                (let [iso2 (aget o "alpha-2")]
                                  (when (blank->nil iso2)
                                    [iso2
                                     (cond-> {:name           (aget o "name")
                                              :region-m49     (blank->nil (aget o "region-code"))
                                              :region-name    (blank->nil (aget o "region"))
                                              :subregion-m49  (blank->nil (aget o "sub-region-code"))
                                              :subregion-name (blank->nil (aget o "sub-region"))}
                                       (blank->nil (aget o "intermediate-region"))
                                       (assoc :intermediate-name (aget o "intermediate-region")))])))
                              rows))
                header (str ";; hayari 流行 — ISO 3166-1 alpha-2 -> UN M49 region / sub-region.\n"
                            ";;\n"
                            ";; GENERATED by scripts/gen_regions.cljs — do not hand-edit.\n"
                            ";; source:  " source-url "\n"
                            ";; fetched: " (subs today 0 10) "\n"
                            ";; records: " (count m) "\n"
                            ";;\n"
                            ";; Countries whose region-m49 is nil (Antarctica) are kept, not dropped:\n"
                            ";; a missing region is a property of the standard, and removing the row\n"
                            ";; would turn it into an absence the caller cannot see.\n\n")]
            (fs/writeFileSync "data/m49-regions.edn"
                              (str header (with-out-str (pp/pprint m))))
            (println "wrote data/m49-regions.edn —" (count m) "countries"))))
      (.catch (fn [e]
                (js/console.error "gen-regions failed:" (str e))
                (set! (.-exitCode js/process) 1)))))

(-main)
